name: Font Library
baseurl: /font-library
url: http://katydecorah.com
description: An open source project to tag and organize Google Fonts.
permalink: pretty
image:
github: https://github.com/katydecorah/font-library

angular: 1.3.15

exclude:
  - "*.lock"
  - "Gemfile"
  - ".scss-lint.yml"
  - "Rakefile"
  - ".travis.yml"

sass:
  style: :compressed