name: Font Library
baseurl: /font-library
url: http://katydecorah.com
description: An open source project to tag and organize Google Fonts.
permalink: pretty
image:
github: https://github.com/katydecorah/font-library

jquery: 2.1.3
angular: 1.3.15

exclude: ["*.lock","Gemfile"]

sass:
  style: :compressed