name: Font Library
baseurl: /font-library
url: http://katydecorah.com
description: An open source project to tag and organize Google fonts.
permalink: pretty
image:
github:

jquery: 2.1.3
angular: 1.3.15
fa: 4.3.0

exclude: ["*.lock","Gemfile"]

sass:
  style: :compressed